export const LIST_REGISTER_USER = [
  { name: "username", type: "text",placeholder: "nombres"  },
  { name: "user_last_name", type: "text",placeholder: "Apellido" },
  { name: "email", type: "email",placeholder: "Correo electrónico" },
  { name: "password", type: "password",placeholder: "Escriba tu contraseña" },
  { name: "password2", type: "password" ,placeholder: "Confirma la contraseña"},
  { name: "telephone", type: "tel" ,placeholder: "Telefono o celular"},
  { name: "birthdate", type: "date",placeholder: "Fecha de Nacimiento"},
  { name: "dni", type: "text",placeholder: "Número de identificación" },
];

export const LIST_REGISTER_JAC = [
  { name: "username", type: "text", placeholder: "nombre de la junta" },
  { name: "email", type: "email", placeholder: "Correo electrónico" },
  { name: "password", type: "password", placeholder: "Escriba tu contraseña" },
  {
    name: "password2",
    type: "password",
    placeholder: "Confirma la contraseña",
  },
  { name: "personery", type: "text", placeholder: "Personeria" },
  { name: "telephone", type: "tel", placeholder: "Telefono o celular" },
  { name: "commune", type: "number", placeholder: "comuna" },
  { name: "neighborhood", type: "text", placeholder: "Barrio" },
];

export const LIST_PERFIL_JAC = [
  {
    name: "username",
    type: "text",
    disabled: true,
    field: "",
    label: "Nombre:",
  },
  { name: "email", type: "email", field: "", label: "Correo electrónico:" },
  { name: "personery", type: "text", field: "", label: "Personeria:" },
  { name: "telephone", type: "tel", field: "", label: "Teléfono:" },
  {
    name: "commune",
    type: "number",
    disabled: true,
    field: "",
    label: "Comuna:",
  },
  {
    name: "neighborhood",
    type: "text",
    disabled: true,
    field: "",
    label: "Barrio:",
  },
  {
    name: "password",
    type: "password",
    field: "",
    placeholder: "*********",
    label: "Nueva Contraseña:",
  },
  {
    name: "password2",
    type: "password",
    field: "",
    placeholder: "*********",
    label: "Comprobar Contraseña:",
  },
];

export const SETTINGS_JAC = ["cuenta", "integrantes"];

export const SETTINGS_JACS = [
  { text: "cuenta", rute: "/settings/cuenta" },
  { text: "integrantes", rute: "/settings/integrantes" },
];

export const SETTINGS_USERS = [{ text: "cuenta", rute: "/settings/cuenta" }];

export const FIELDS_PROYECT = [
  { text: "Proyecto", rute: "#" },
  { text: "Proyectos", rute: "#proyectos" },
];

export const LIST_ROLES = ["presidente", "vicepresidente", "tesorero", "secretario", "coordinador"]
export const WORD_LIST = [
  "Terrón Colorado",
  "Vista Hermosa",
  "Sector Patio Bonito",
  "Aguacatal",
  "ciudad jardin",
  "Santa Rita",
  "Santa Teresita",
  "Arboledas",
  "Normandía",
  "Juanambú",
  "Centenario",
  "Granada",
  "Versalles",
  "San Vicente",
  "Santa Mónica",
  "Prados del Norte",
  "La Flora",
  "La Campiña",
  "La Paz",
  "El Bosque",
  "Menga",
  "Ciudad Los Alamos",
  "Chipichape",
  "Brisas de los Alamos",
  "Urbanización La Merced",
  "Vipasa",
  "Urbanización La Flora",
  "Altos de Menga",
  "Sector Altos Normandía",
  "Senderos de la Flora",
  "El Nacional",
  "El Peñón",
  "San Antonio",
  "San Cayetano",
  "Los Libertadores",
  "San Juan Bosco",
  "Santa Rosa",
  "La Merced",
  "San Pascual",
  "El Calvario",
  "San Pedro",
  "San Nicolas",
  "El Hoyo",
  "El Piloto",
  "Navarro - La Chanca",
  "Jorge Isaacs",
  "Santander",
  "Porvenir",
  "Las Delicias",
  "Manzanares",
  "Salomia",
  "Fátima",
  "Sultana - Berlín - San Francisco",
  "Popular",
  "Ignacio Rengifo",
  "Guillermo Valencia",
  "La Isla",
  "Marco Fidel Suárez",
  "Evaristo García",
  "La Esmeralda",
  "Bolivariano",
  "Olaya Herrera",
  "Unidad Residencial Bueno Madrid",
  "Flora Industrial",
  "Calima",
  "Industria de Licores",
  "La Alianza",
  "El Sena",
  "Los Andes",
  "Los Guayacanes",
  "Chiminangos Segunda Etapa",
  "Chiminangos Primera Etapa",
  "Metropolitano del Norte",
  "Los Parques - Barranquilla",
  "Villa del Sol",
  "Paseo de Los Almendros",
  "Los Andes B - La Riviera",
  "Torres de Comfandi",
  "Villa del Prado - El Guabito",
  "San Luís",
  "Jorge Eliecer Gaitán",
  "Paso del Comercio",
  "Los Alcázares",
  "Petecuy Primera Etapa",
  "Petecuy Segunda Etapa",
  "La Rivera Primera Etapa",
  "Los Guaduales",
  "Petecuy Tercera Etapa",
  "Ciudadela Floralia",
  "Fonaviemcali",
  "San Luís II",
  "Urbanización Calimio",
  "Sector Puente del Comercio",
  "Alfonso López P. 1a. Etapa",
  "Alfonso López P. 2a. Etapa",
  "Alfonso López P. 3a. Etapa",
  "Puerto Nuevo",
  "Puerto Mallarino",
  "Urbanización El Angel del Hogar",
  "Siete de Agosto",
  "Los Pinos",
  "San Marino",
  "Las Ceibas",
  "Base Aérea",
  "Parque de la Caña",
  "Fepicol",
  "Primitivo Crespo",
  "Simón Bolívar",
  "Saavedra Galindo",
  "Uribe Uribe",
  "Santa Mónica Popular",
  "La Floresta",
  "Benjamín Herrera",
  "Municipal",
  "Industrial",
  "El Troncal",
  "Las Américas",
  "Atanasio Girardot",
  "Santa Fe",
  "Chapinero",
  "Villa Colombia",
  "EL Trébol",
  "La Base",
  "Urbanización La Nueva Base",
  "Alameda",
  "Bretaña",
  "Junín",
  "Guayaquil",
  "Aranjuez",
  "Manuel María Buenaventura",
  "Santa Mónica Belalcázar",
  "Belalcázar",
  "Sucre",
  "Barrio Obrero",
  "El Dorado",
  "El Guabal",
  "La Libertad",
  "Santa Elena",
  "Las Acacias",
  "Santo Domingo",
  "Jorge Zawadsky",
  "Olímpico",
  "Cristóbal Colón",
  "La Selva",
  "Barrio Departamental",
  "Pasoancho",
  "Panamericano",
  "Colseguros Andes",
  "San Cristobal",
  "Las Granjas",
  "San Judas Tadeo I Etapa",
  "San Judas Tadeo II Etapa",
  "San Carlos",
  "Maracaibo",
  "La Independencia",
  "La Esperanza",
  "Urbanización Boyacá",
  "El Jardín",
  "La Fortaleza",
  "El Recuerdo",
  "Aguablanca",
  "El Prado",
  "20 de Julio",
  "Prados de Oriente",
  "Los Sauces",
  "Villa del Sur",
  "José Holguín Garcés",
  "León XIII",
  "José María Cordoba",
  "San Pedro Claver",
  "Los Conquistadores",
  "La Gran Colombia",
  "San Benito",
  "Primavera",
  "Villanueva",
  "Asturias",
  "Eduardo Santos",
  "Alfonso Barberena A.",
  "El Paraiso",
  "Fenalco Kennedy",
  "Nueva Floresta",
  "Julio Rincón",
  "Doce de Octubre",
  "El Rodeo",
  "Sindical",
  "Bello Horizonte",
  "Ulpiano Lloreda",
  "El Vergel",
  "El Poblado I",
  "El Poblado II",
  "Los Comuneros Segunda Etapa",
  "Ricardo Balcázar",
  "Omar Torrijos",
  "El Diamante",
  "Lleras Restrepo",
  "Villa del Lago",
  "Los Robles",
  "Rodrigo Lara Bonilla",
  "Charco Azul",
  "Villablanca",
  "Calipso",
  "Yira Castro",
  "Lleras Restrepo II Etapa",
  "Marroquín III",
  "Los Lagos",
  "Sector Laguna del Pondaje",
  "El Pondaje",
  "Sector Asprosocial-Diamante",
  "Alfonso Bonilla Aragón",
  "Alirio Mora Beltrán",
  "Manuela Beltrán",
  "Las Orquídeas",
  "José Manuel Marroquín Segunda Etapa",
  "José Manuel Marroquín Primera Etapa",
  "Puerta del Sol",
  "Los Naranjos I",
  "Promociones Populares B",
  "Los Naranjos II",
  "El Retiro",
  "Comuneros I",
  "Laureano Gómez",
  "El Vallado",
  "Ciudad Cordoba",
  "Mojica",
  "El Morichal",
  "Mariano Ramos",
  "República de Israel",
  "Unión de Vivienda Popular",
  "Antonio Nariño",
  "Brisas del Limonar",
  "Vendimia",
  "Ciudad 2000",
  "La Alborada",
  "La Playa",
  "Primero de Mayo",
  "Ciudadela Comfandi",
  "Ciudad Universitaria",
  "Caney",
  "Lili",
  "Santa Anita - La Selva",
  "El Ingenio",
  "Ciudad Capri",
  "La Hacienda",
  "El Limonar",
  "Buenos Aires",
  "Barrio Caldas",
  "Los Chorros",
  "Meléndez",
  "Los Farallones",
  "Francisco Eladio Ramirez",
  "El Refugio",
  "La Cascada",
  "El Lido",
  "Urbanización Tequendama",
  "Barrio Eucarístico",
  "El Cortijo",
  "Belisario Caicedo",
  "Siloé",
  "Lleras Camargo",
  "Belén",
  "Brisas de Mayo",
  "Tierra Blanca",
  "Pueblo Joven",
  "Pízamos I",
  "Pízamos II",
  "Calimio Desepaz",
  "El Remanso",
  "Los Líderes",
  "Desepaz Invicali",
  "Compartir",
  "Ciudad Talanga",
];
